SHELL = cmd.exe

#
# ZDS II Make File - DemoAgonC project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.3.5 (Build 23020901)
#   IDE component: d:5.3.0:23020901
#   Install Path: C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\
#

RM = del

# ZDS base directory
ZDSDIR = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5
ZDSDIR_ESCSPACE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5

# ZDS bin directory
BIN = $(ZDSDIR)\bin

# ZDS include base directory
INCLUDE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\include
INCLUDE_ESCSPACE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\include

# ZTP base directory
ZTPDIR = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\ZTP2.5.1
ZTPDIR_ESCSPACE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\ZTP2.5.1

# project directory
PRJDIR = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Demo\DemoAgonC
PRJDIR_ESCSPACE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Demo\DemoAgonC

# intermediate files directory
WORKDIR = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Demo\DemoAgonC\Debug
WORKDIR_ESCSPACE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Demo\DemoAgonC\Debug

# output files directory
OUTDIR = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Demo\DemoAgonC\Debug\
OUTDIR_ESCSPACE = C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Demo\DemoAgonC\Debug\

# tools
CC = @"$(BIN)\eZ80cc"
AS = @"$(BIN)\eZ80asm"
LD = @"$(BIN)\eZ80link"
AR = @"$(BIN)\eZ80lib"
WEBTOC = @"$(BIN)\mkwebpage"

CFLAGS =  \
-define:_DEBUG -define:_EZ80F92 -define:_EZ80ACCLAIM!  \
-define:ZDSII_EZ80_AGON -define:_SIMULATE -NOgenprintf -keepasm  \
-NOkeeplst -NOlist -NOlistinc -NOmodsect -optspeed -promote  \
-reduceopt  \
-stdinc:"\"..;..\..\..\Source\include;..\..\..\Source\portable\ThirdParty\Community  \
-Supported  \
-Ports\ZDSII\eZ80AgonLight;..\..\..\..\..\..\..\..\ZDSII_eZ80Acclaim!_5.3.5\include\std;..\..\..\..\..\..\..\..\ZDSII_eZ80Acclaim!_5.3.5\include\zilog\""  \
-usrinc:"\"..;\"" -NOmultithread -NOpadbranch -debug -cpu:eZ80F92  \
-asmsw:"   \
	-define:_EZ80ACCLAIM!=1 -define:_SIMULATE=1  \
	-include:\"..;..\..\..\..\..\..\..\..\ZDSII_eZ80Acclaim!_5.3.5\include\std;..\..\..\..\..\..\..\..\ZDSII_eZ80Acclaim!_5.3.5\include\zilog\"  \
	-NOlist -NOlistmac -pagelen:0 -pagewidth:80 -quiet -NOsdiopt  \
	-warn -debug -NOigcase -cpu:eZ80F92"

ASFLAGS =  \
-define:_EZ80ACCLAIM!=1 -define:_SIMULATE=1  \
-include:"\"..;..\..\..\..\..\..\..\..\ZDSII_eZ80Acclaim!_5.3.5\include\std;..\..\..\..\..\..\..\..\ZDSII_eZ80Acclaim!_5.3.5\include\zilog\""  \
-NOlist -NOlistmac -name -pagelen:0 -pagewidth:80 -quiet  \
-NOsdiopt -warn -debug -NOigcase -cpu:eZ80F92

LDFLAGS = @..\Debug.linkcmd
build: DemoAgonC relist

buildall: clean DemoAgonC relist

relink: deltarget DemoAgonC

deltarget: 
	@if exist "$(WORKDIR)\Hello World.lod"  \
            $(RM) "$(WORKDIR)\Hello World.lod"
	@if exist "$(WORKDIR)\Hello World.hex"  \
            $(RM) "$(WORKDIR)\Hello World.hex"
	@if exist "$(WORKDIR)\Hello World.map"  \
            $(RM) "$(WORKDIR)\Hello World.map"

clean: 
	@if exist "$(WORKDIR)\Hello World.lod"  \
            $(RM) "$(WORKDIR)\Hello World.lod"
	@if exist "$(WORKDIR)\Hello World.hex"  \
            $(RM) "$(WORKDIR)\Hello World.hex"
	@if exist "$(WORKDIR)\Hello World.map"  \
            $(RM) "$(WORKDIR)\Hello World.map"
	@if exist "$(WORKDIR)\init.obj"  \
            $(RM) "$(WORKDIR)\init.obj"
	@if exist "$(WORKDIR)\init.lis"  \
            $(RM) "$(WORKDIR)\init.lis"
	@if exist "$(WORKDIR)\init.lst"  \
            $(RM) "$(WORKDIR)\init.lst"
	@if exist "$(WORKDIR)\mosvec24.obj"  \
            $(RM) "$(WORKDIR)\mosvec24.obj"
	@if exist "$(WORKDIR)\mosvec24.lis"  \
            $(RM) "$(WORKDIR)\mosvec24.lis"
	@if exist "$(WORKDIR)\mosvec24.lst"  \
            $(RM) "$(WORKDIR)\mosvec24.lst"
	@if exist "$(WORKDIR)\FPDUMY.obj"  \
            $(RM) "$(WORKDIR)\FPDUMY.obj"
	@if exist "$(WORKDIR)\FPDUMY.lis"  \
            $(RM) "$(WORKDIR)\FPDUMY.lis"
	@if exist "$(WORKDIR)\FPDUMY.lst"  \
            $(RM) "$(WORKDIR)\FPDUMY.lst"
	@if exist "$(WORKDIR)\main.obj"  \
            $(RM) "$(WORKDIR)\main.obj"
	@if exist "$(WORKDIR)\main.lis"  \
            $(RM) "$(WORKDIR)\main.lis"
	@if exist "$(WORKDIR)\main.lst"  \
            $(RM) "$(WORKDIR)\main.lst"
	@if exist "$(WORKDIR)\main.src"  \
            $(RM) "$(WORKDIR)\main.src"
	@if exist "$(WORKDIR)\list.obj"  \
            $(RM) "$(WORKDIR)\list.obj"
	@if exist "$(WORKDIR)\list.lis"  \
            $(RM) "$(WORKDIR)\list.lis"
	@if exist "$(WORKDIR)\list.lst"  \
            $(RM) "$(WORKDIR)\list.lst"
	@if exist "$(WORKDIR)\list.src"  \
            $(RM) "$(WORKDIR)\list.src"
	@if exist "$(WORKDIR)\queue.obj"  \
            $(RM) "$(WORKDIR)\queue.obj"
	@if exist "$(WORKDIR)\queue.lis"  \
            $(RM) "$(WORKDIR)\queue.lis"
	@if exist "$(WORKDIR)\queue.lst"  \
            $(RM) "$(WORKDIR)\queue.lst"
	@if exist "$(WORKDIR)\queue.src"  \
            $(RM) "$(WORKDIR)\queue.src"
	@if exist "$(WORKDIR)\stream_buffer.obj"  \
            $(RM) "$(WORKDIR)\stream_buffer.obj"
	@if exist "$(WORKDIR)\stream_buffer.lis"  \
            $(RM) "$(WORKDIR)\stream_buffer.lis"
	@if exist "$(WORKDIR)\stream_buffer.lst"  \
            $(RM) "$(WORKDIR)\stream_buffer.lst"
	@if exist "$(WORKDIR)\stream_buffer.src"  \
            $(RM) "$(WORKDIR)\stream_buffer.src"
	@if exist "$(WORKDIR)\croutine.obj"  \
            $(RM) "$(WORKDIR)\croutine.obj"
	@if exist "$(WORKDIR)\croutine.lis"  \
            $(RM) "$(WORKDIR)\croutine.lis"
	@if exist "$(WORKDIR)\croutine.lst"  \
            $(RM) "$(WORKDIR)\croutine.lst"
	@if exist "$(WORKDIR)\croutine.src"  \
            $(RM) "$(WORKDIR)\croutine.src"
	@if exist "$(WORKDIR)\timers.obj"  \
            $(RM) "$(WORKDIR)\timers.obj"
	@if exist "$(WORKDIR)\timers.lis"  \
            $(RM) "$(WORKDIR)\timers.lis"
	@if exist "$(WORKDIR)\timers.lst"  \
            $(RM) "$(WORKDIR)\timers.lst"
	@if exist "$(WORKDIR)\timers.src"  \
            $(RM) "$(WORKDIR)\timers.src"
	@if exist "$(WORKDIR)\event_groups.obj"  \
            $(RM) "$(WORKDIR)\event_groups.obj"
	@if exist "$(WORKDIR)\event_groups.lis"  \
            $(RM) "$(WORKDIR)\event_groups.lis"
	@if exist "$(WORKDIR)\event_groups.lst"  \
            $(RM) "$(WORKDIR)\event_groups.lst"
	@if exist "$(WORKDIR)\event_groups.src"  \
            $(RM) "$(WORKDIR)\event_groups.src"
	@if exist "$(WORKDIR)\heap_3.obj"  \
            $(RM) "$(WORKDIR)\heap_3.obj"
	@if exist "$(WORKDIR)\heap_3.lis"  \
            $(RM) "$(WORKDIR)\heap_3.lis"
	@if exist "$(WORKDIR)\heap_3.lst"  \
            $(RM) "$(WORKDIR)\heap_3.lst"
	@if exist "$(WORKDIR)\heap_3.src"  \
            $(RM) "$(WORKDIR)\heap_3.src"
	@if exist "$(WORKDIR)\port.obj"  \
            $(RM) "$(WORKDIR)\port.obj"
	@if exist "$(WORKDIR)\port.lis"  \
            $(RM) "$(WORKDIR)\port.lis"
	@if exist "$(WORKDIR)\port.lst"  \
            $(RM) "$(WORKDIR)\port.lst"
	@if exist "$(WORKDIR)\port.src"  \
            $(RM) "$(WORKDIR)\port.src"
	@if exist "$(WORKDIR)\tasks.obj"  \
            $(RM) "$(WORKDIR)\tasks.obj"
	@if exist "$(WORKDIR)\tasks.lis"  \
            $(RM) "$(WORKDIR)\tasks.lis"
	@if exist "$(WORKDIR)\tasks.lst"  \
            $(RM) "$(WORKDIR)\tasks.lst"
	@if exist "$(WORKDIR)\tasks.src"  \
            $(RM) "$(WORKDIR)\tasks.src"

relist: 

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR_ESCSPACE)\init.obj  \
            $(WORKDIR_ESCSPACE)\mosvec24.obj  \
            $(WORKDIR_ESCSPACE)\FPDUMY.obj  \
            $(WORKDIR_ESCSPACE)\main.obj  \
            $(WORKDIR_ESCSPACE)\list.obj  \
            $(WORKDIR_ESCSPACE)\queue.obj  \
            $(WORKDIR_ESCSPACE)\stream_buffer.obj  \
            $(WORKDIR_ESCSPACE)\croutine.obj  \
            $(WORKDIR_ESCSPACE)\timers.obj  \
            $(WORKDIR_ESCSPACE)\event_groups.obj  \
            $(WORKDIR_ESCSPACE)\heap_3.obj  \
            $(WORKDIR_ESCSPACE)\port.obj  \
            $(WORKDIR_ESCSPACE)\tasks.obj

DemoAgonC: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR_ESCSPACE)\init.obj :  \
            $(PRJDIR_ESCSPACE)\init.asm
	 $(AS) $(ASFLAGS) "$(PRJDIR)\init.asm"

$(WORKDIR_ESCSPACE)\mosvec24.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\mosvec24.asm  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\mos_api.inc
	 $(AS) $(ASFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\mosvec24.asm"

$(WORKDIR_ESCSPACE)\FPDUMY.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\src\rtl\common\FPDUMY.ASM
	 $(AS) $(ASFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\ZDSII_eZ80Acclaim!_5.3.5\src\rtl\common\FPDUMY.ASM"

$(WORKDIR_ESCSPACE)\main.obj :  \
            $(PRJDIR_ESCSPACE)\main.c  \
            $(INCLUDE_ESCSPACE)\std\Format.h  \
            $(INCLUDE_ESCSPACE)\std\Stdarg.h  \
            $(INCLUDE_ESCSPACE)\std\Stdio.h
	 $(CC) $(CFLAGS) "$(PRJDIR)\main.c"

$(WORKDIR_ESCSPACE)\list.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\list.c  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\list.c"

$(WORKDIR_ESCSPACE)\queue.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\queue.c  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h  \
            $(INCLUDE_ESCSPACE)\std\String.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\queue.c"

$(WORKDIR_ESCSPACE)\stream_buffer.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\stream_buffer.c  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\include\stdint.h  \
            $(INCLUDE_ESCSPACE)\std\String.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\stream_buffer.c"

$(WORKDIR_ESCSPACE)\croutine.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\croutine.c
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\croutine.c"

$(WORKDIR_ESCSPACE)\timers.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\timers.c  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\timers.c"

$(WORKDIR_ESCSPACE)\event_groups.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\event_groups.c  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\event_groups.c"

$(WORKDIR_ESCSPACE)\heap_3.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\MemMang\heap_3.c  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\MemMang\heap_3.c"

$(WORKDIR_ESCSPACE)\port.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\port.c  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\portmacro.h  \
            $(INCLUDE_ESCSPACE)\std\Format.h  \
            $(INCLUDE_ESCSPACE)\std\Stdarg.h  \
            $(INCLUDE_ESCSPACE)\std\Stdio.h  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h  \
            $(INCLUDE_ESCSPACE)\zilog\cio.h  \
            $(INCLUDE_ESCSPACE)\zilog\defines.h  \
            $(INCLUDE_ESCSPACE)\zilog\eZ80190.h  \
            $(INCLUDE_ESCSPACE)\zilog\eZ80F91.h  \
            $(INCLUDE_ESCSPACE)\zilog\eZ80F92.h  \
            $(INCLUDE_ESCSPACE)\zilog\eZ80F93.h  \
            $(INCLUDE_ESCSPACE)\zilog\eZ80L92.h  \
            $(INCLUDE_ESCSPACE)\zilog\ez80.h  \
            $(INCLUDE_ESCSPACE)\zilog\gpio.h  \
            $(INCLUDE_ESCSPACE)\zilog\uart.h  \
            $(INCLUDE_ESCSPACE)\zilog\uartdefs.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\port.c"

$(WORKDIR_ESCSPACE)\tasks.obj :  \
            C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\tasks.c  \
            $(INCLUDE_ESCSPACE)\std\Format.h  \
            $(INCLUDE_ESCSPACE)\std\Stdarg.h  \
            $(INCLUDE_ESCSPACE)\std\Stdio.h  \
            $(INCLUDE_ESCSPACE)\std\Stdlib.h  \
            $(INCLUDE_ESCSPACE)\std\String.h
	 $(CC) $(CFLAGS) "C:\Users\jrose\tech_stuff\retro\Zilog\eZ80\AgonLight\programming\FreeRTOS\FreeRTOSv202212.01-LTS\FreeRTOS\Source\portable\ThirdParty\Community-Supported-Ports\ZDSII\eZ80AgonLight\tasks.c"

